[project]
name = "c2-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "NayuTW", email = "trevordwilliams10@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
c2-project = "c2_project:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "c2"
